version: '3'

services:
    nginx:
        build: ./nginx
        environment:
            - TZ=Asia/Seoul
        volumes:
            - static_volume:/usr/src/app/_static
        ports:
            - 80:80
        depends_on:
            - web
    web:
        build: .
        environment:
            - TZ=Asia/Seoul
        command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/usr/src/app/_static
            - ./:/usr/src/app
        expose:
            - 8000
        env_file:
            - ./.env.prod
        depends_on:
            - db
    db:
        environment:
            - TZ=Asia/Seoul
            - PGTZ=Asia/Seoul
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.prod.db
volumes:
    postgres_data:
    static_volume:
