version: '3'

services:
    web:
        build: .
        command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - ./:/usr/src/app
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev
        depends_on:
            - db
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=mipo
            - POSTGRES_PASSWORD=mipo_0522337424
            - POSTGRES_DB=mipochurch_room_reservation_dev
volumes:
    postgres_data:
