version: '3'

services:
    nginx:
        build: ./nginx
        environment:
            - TZ=Asia/Seoul
        volumes:
            - static_volume:/usr/src/app/_static
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        ports:
            - 80:80
            - 443:443
        depends_on:
            - web
    certbot:
        image: certbot/certbot:arm64v8-latest
        environment:
            - TZ=Asia/Seoul
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
    web:
        build: .
        environment:
            - TZ=Asia/Seoul
        command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/usr/src/app/_static
            - ./:/usr/src/app
        expose:
            - 8000
        env_file:
            - ./.env.prod
        depends_on:
            - db
    db:
        environment:
            - TZ=Asia/Seoul
            - PGTZ=Asia/Seoul
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.prod.db
volumes:
    postgres_data:
    static_volume:
